### ISSUE TITLE
DCM in Cuk Converter

### ISSUE THREAD

**Issue by ghandeb** [odtu/ee464#1]
@ozank 

Inductance değerini çok düşürmek converterı DCM'e sokar mı hocam?
Veya inductance üzerinde sabit akım olmasını voltajın sıfırlanmasını nasıl açıklarız?

Bu da böyle ramazan sohbetleri sorusu gibi oldu ama.

**Comment by MelisaSarici** [comment]
@ozank 
Inductance değeri çok düştüğünde DCM olmuyor da akım ters yöne akmaya başlıyor. Inductance değerini de bu akım hep pozitif kalacak şekilde seçince Vout hiç 15 V olmuyor?

**Comment by ozank** [comment]
Düşük inductance değeri o sorunu yaratır. Uygun bir değer seçmeniz gerekiyor. Hızlıca bir tasarım yapmak isterseniz Plex'de kullanabilirsiniz
https://www.plexim.com/academy/power-electronics/cuk-conv

Faydalı olabilecek bir kaç link
http://www.ese.iitb.ac.in/~suryad/lectures/EN206/Lecture-DC-DCConverter-2.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.412.8076&rep=rep1&type=pdf
http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=633459
