### ISSUE TITLE
Steinmetz formülü 

### ISSUE THREAD

**Issue by burakkemalkara** [odtu/ee464#10]
Steinmetz formülünde göre bulmuş olduğumuz  loss, core magnetic reactance
ile core resistance üzerinde harcanan kayıpların toplamı mı oluyor?

**Comment by tokgozfurkan** [comment]
Merhabalar Burak. Core magnetizing reactance ideal kabul edildiği için orda loss olmadığını varsayıyoruz. Ona parallel olan Rc core lossu represent etmesi için modele ekleniyor. Bu core lossun içinde hysteresis ve eddy losslar var. Steinmetz ile bulduğun hysteresis loss değeri oluyor.  Hatırlamak  istersen [361](http://keysan.me/presentations/ee361_practical_transformers.html#1) notlarına göz gezdirebilirsin.

**Comment by burakkemalkara** [comment]
Teşekkürler hocam anladım
