### ISSUE TITLE
Al değeri ile inductance hesabı

### ISSUE THREAD

**Issue by burakkemalkara** [odtu/ee464#11]
Nüvenin Al değerinden bulduğumuz inductance, leakage inductance mı?

**Comment by ghandeb** [comment]
Inductance factor olarak verilen değer aslında core dimensionları ve relative permeabilitysinin çarpım bölümünden oluşur, yani aslında core'un içinden giden fluxları ne kadar link edebileceğini bulursun. Bu da bir trafo için magnetizing inductance'a denk geliyor.

**Comment by burakkemalkara** [comment]
Teşekkür ederim hocam anladım
