### ISSUE TITLE
core loss?

### ISSUE THREAD

**Issue by MERTAYDIN46** [odtu/ee464#12]
hocam merhaba,
steinmetz's equation da frekansın hem core lossu hem de eddy lossu etkilediğinden equationa eklendiğinden bahsetmiştik fakat ericson's transformer design notunda frekansı hiç katmamış işin içine? ben tam olarak neyi ihmal ettiğinide anlamadım. yardımcı olursanız çok sevinirim.
iyi günler.

![Ekran Alıntısı](https://user-images.githubusercontent.com/44820316/77854878-8b869280-71f5-11ea-85f8-0de640c8d7c7.PNG)

**Comment by tokgozfurkan** [comment]
Merhabalar Mert,
Frekansı hesaba katmış aslına bakarsan. Yolladığın formülün birkaç sayfa ilerisinde aşağıdaki gibi bir şey demiş. Yani frekans aslında formülün içinde var ama K ve beta katsayıları olarak varlar. Bana kalırsa biraz karışık anlatmış transformer tasarımını. Diğer kaynaklara bakmayı deneyebilirsin veya üreticinin design guidelarına da bakabilirsin. 

![Annotation 2020-03-29 195620](https://user-images.githubusercontent.com/26572692/77855166-62ff9800-71f7-11ea-8a08-5b67ab3ef969.png)

**Comment by MERTAYDIN46** [comment]
teşekkürler 
bir sorum daha vardı da yine aynı equation da delta_B değeri sanki sadece positive region da salınım yaparken verilmiş fakat B değeri eksiye simetrik şekilde düşünce (push pull daki gibi) positive delta_B nin yarısını equationa koyup bulduğumuz sonucu 2 ile çarpacağız gibi hissettim yanılıyor muyum acaba?

**Comment by tokgozfurkan** [comment]
Merhabalar Mert,
Örnekte izole Cuk converter yapıyor. Burda trafo sadece pozitif cycleda çalıştığı için B-H curveün pozitif tarafını tarıyor. Ama push-pull gibi simetrik bir converter olsaydı hem negatif hem pozitif tarafta çalışacaktı. Push-pull örneğinde pozitif cycledaki core lossu bulup ikiyle çarpmak toplam core lossa eşit oluyor.
