### ISSUE TITLE
AC resistance

### ISSUE THREAD

**Issue by OgunAltun** [odtu/ee464#13]
Trafo için kablomuzu https://www.powerstream.com/Wire_Size.htm sitesindeki maximum frekansa uygun olarak seçersek AC resistance'ı DC resistance'a eşit olarak alabilir miyiz?

**Comment by tokgozfurkan** [comment]
Merhabalar Ogün,
Sunumda da anlattığımız gibi skin effect tek etken değil AC direnci etkileyen. Proximity effect tahmin edemeyeceğin AC dirençlerle karşılaşmana sebebiyet verebilir. Onu hesaplamak istersen Dowell Curve nedir diye bir araştırabilirsin googledan.

**Comment by OgunAltun** [comment]
Simülasyon projesi için proximity effect ihmal edilebilir yazıyordu. Bu durumda dc-ac dirençleri eşit alabilirim anladığım kadarıyla. Teşekkürler hocam.
