### ISSUE TITLE
chassis current.

### ISSUE THREAD

**Issue by MERTAYDIN46** [odtu/ee464#16]
Merhaba hocam bulduğum AWG lerin power transmission için olan max current değerleri benim değerlerimden düşük kalıyor fakat birde max chassis current değeri vermiş sanırım fill factor den feda edilince daha iyi bir soğutma yapmak mümkünmüş bu kablolara. bende max rating leri chassis değerlerine göre alsam sorun olur mu acaba?

**Comment by tokgozfurkan** [comment]
Max current değerini kablonun cross section areası* current density değerinden hesaplayabilirsin. Eğer kablo gereken değeri sağlamıyorsa aynısından birden fazla parallel kullanabilirsin.
