### ISSUE TITLE
Vout

### ISSUE THREAD

**Issue by MelisaSarici** [odtu/ee464#2]
@ozank 
Hocam, teorik olarak hesap edilen Duty cycle verildiğinde Vout değerinin 15 V değil de 14 V gibi bir değer çıkması normal mi?

**Comment by ghandeb** [comment]
@ozank 
bizde de oldu o

**Comment by ozank** [comment]
baktığınız varsayıyorum ama switch ve diyotlar ideal de mi? Üstünde bir gerilim düşmesi olmuyor?

**Comment by ozank** [comment]
Bi de çıkıştaki L-C filtrenin karakteristiği ve anahtarlama frekansının ilişkisine de dikkat edin.

**Comment by berkzorlutuna** [comment]
Switch ideal değil Ozan hocam. Switch direncini 0 yapmaya çalıştık fakat program izin vermedi. 0.001 ohm olarak değer verdik switch direncine. 

iPhone’umdan gönderildi

Ozan K <notifications@github.com> şunları yazdı (16 Mar 2018 17:33):

**Comment by Mertkaracelebi** [comment]
Hocam en ideal halini kurdum devrenin output voltajının 14.96 V olması sorun değildir umarım. Aynı zamanda kullandığımız load constant power load mu olması lazım yoksa constant impedance yük işimizi görür mü ?

**Comment by ozank** [comment]
Sabit direnc uygundur Mert.
