### ISSUE TITLE
Simulink Simscape+Specialized Tech

### ISSUE THREAD

**Issue by orhuntas** [odtu/ee464#22]
Merhaba. Devrenin compansator kısmını normalde kullandığımız libraryde op-amp olmadığı için Furkan Hoca'nın tavsiyesiyle diğer kütüphaneyi kullanarak kurmaya çalıştım fakat simlüasyonu bir türlü çalıştıramıyorum. Output Voltajını Voltage Measurement ile ölçüp Simulink-PS ile fiziksel sinyale dönüştürüp Controlled Voltage Source ile Simscape Electrical componentlarıyla kurduğum compansator devresine beslemeye çalıştım fakat Controlled Voltage Source'un bağlı olduğu bloklar için 
Equations of one or more components may be dependent or inconsistent. This can cause problems in transient initialization. Here is the set of components involved:
hatası veriyor.
Local solver kullanmayı ya da solver ayarlarını değiştirmeyi denedim fakat çözülmedi, bir türlü dikkat etmem gereken ekstra neler var? Hatta bunu yapmayıp Vosc ve Vout yerine farklı değerlerde DC source bağlarsam da aynı hatayı alıyorum. Şimdiden teşekkür ederim

**Comment by furkankarakaya** [comment]
Solver configuration mavi devreye bağlı olmalı. Onu takmadığın için problem yaşıyor olabilirsin.
