### ISSUE TITLE
Hardware Project - PCB design

### ISSUE THREAD

**Issue by OgunAltun** [odtu/ee464#25]
Merhaba Hocam,

Projenin formatı değiştiği aklıma takılan birkaç şey var. Bizim PCB dizayn edebilmemiz için çıkış voltajını ölçüp kontrolcü ile PWM sinyali üretme devresini kurmamız gerekiyor değil mi ? Compensator kısmı bonus olduğu için tüm feedback mekanizması bonus olmadı yani. Çünkü TL494 datasheetinden anladığım kadarıyla istediğimiz çıkış voltajını referans voltağına oranlayacak dirençleri seçmemiz yeterli, compansator devresi tasarlamamız gerekmiyor TL494 için. 

Teşekkürler.

**Comment by ozank** [comment]
Bunu grupta konuşmuştuk ama buraya da yazayım.Hazır bir kontrol entegresi kullanıp, PCB'ye ilgili bağlantıları yaparak kullanabilirsiniz
