### ISSUE TITLE
462-464 Ortak Proje - DC Link Filter

### ISSUE THREAD

**Issue by OgunAltun** [odtu/ee464#26]
Merhaba Hocam,
Ortak projenin ilk kısmında rectifier için DC link filtre tasarımı istiyor. İlk sayfadaki figürde sadece capacitor gösterilmiş. Sadece capacitor mü seçmeliyiz yoksa LC filtre mi tasarlayalım?

**Comment by ozank** [comment]
İstediğiniz tasarımı kullanabilirsiniz. L-C inrush akimi azaltacağı için daha iyi sonuçlar verecektir.
