### ISSUE TITLE
2. soru

### ISSUE THREAD

**Issue by yusufbyilmaz** [odtu/ee464#3]
Hocam 2. sorunun b şıkkında inputu hala 48 kullanmıycaz de mi? input sadece a şıkkı için mi geçerli?

**Comment by ozank** [comment]
Aynı gerilimi kullanacaksınız diye düşünmüştüm. Sıkıntı nedir?

**Comment by yusufbyilmaz** [comment]
Hocam soruyu çok yanlış anlamışım, sonradan anlayınca hallettim. İssueyu kapatmayı unutmuşum. Teşekkürler.
