### ISSUE TITLE
Project 1 Q2 b

### ISSUE THREAD

**Issue by MERTAYDIN46** [odtu/ee464#6]
Hocam merhaba,
Projede 2.nci sorunun b şıkkında Voltage ripple a karşılık gelen capacitance değerini hesaplamamız için 2.nci inductor ın değerini bilmemiz gerekmiyor mu ?

**Comment by tokgozfurkan** [comment]
Merhabalar Mert,

Q2 part b ve c'nin sıralaması değiştirildi. Şimdi hesaplayabilirsin.
