### ISSUE TITLE
p1-Transient performansı

### ISSUE THREAD

**Issue by orhuntas** [odtu/ee464#7]
Geçen dönemki projelerde grafiklerin steady-state'te çizilmesi gerekiyordu fakat ilk projede böyle bir ifade geçmemiş. Transient'larda olanları da dikkate almalı mıyız-özellikle component seçiminde-, yoksa steady-state'e göre değerlendirip seçim yapmamız yeterli mi? @tokgozfurkan @furkankarakaya

**Comment by tokgozfurkan** [comment]
Merhaba Orhun,
Grafikleri steady-state'de çizdirmelisin ancak component seçiminde transientları da dikkate almalısın. Component seçimi kısmına neden öyle seçtiğini de eklersen bir sıkıntı olmaz.
