### ISSUE TITLE
Trafonun teorik değerleri

### ISSUE THREAD

**Issue by burakkemalkara** [odtu/ee464#9]
Trafonun  Core-loss resistance ve  Magnetizing reactance değerlerini nasıl bulabileceğimi
bulamadım, internette de çok araştırdım. Pratik olarak ölçüp
bulabiliyorduk 361 dersinde. Teorik olarak bulmanın da bi yolu var mı?

**Comment by ghandeb** [comment]
Bir önceki yorumda da belirttiğim gibi, aslında teorik olarak hesapladığın inductance magnetizing inductance.
